spring:
  application:
    name: kyn-configuration-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wittgroup-inc/kyn-configurations.git
          clone-on-start: true
          username:
          password:
server:
  port: 8888
eureka:
  instance:
    hostname: localhost
